# Generated by Django 3.2.8 on 2021-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20211030_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=120, verbose_name='novel name'),
        ),
    ]
