# Generated by Django 3.2.8 on 2021-10-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='name',
        ),
    ]
